import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { fetchReports, generateReport } from './reportSlice'
import DataTable from '../../components/common/DataTable'
import StatusBadge from '../../components/common/StatusBadge'
import styles from '../dashboard/DashboardPage.module.css'

const columns = [
  { key: 'id', label: 'Report ID' },
  { key: 'name', label: 'Name' },
  { key: 'type', label: 'Type' },
  { key: 'generatedBy', label: 'Generated By' },
  { key: 'createdAt', label: 'Date' },
  { key: 'status', label: 'Status', render: v => <StatusBadge status={v} /> }
]

const ReportCenterPage = () => {
  const dispatch = useDispatch()
  const { reports, loading, generating } = useSelector(state => state.reports)

  useEffect(() => { dispatch(fetchReports()) }, [dispatch])

  return (
    <div className={styles.page}>
      <div className={styles.pageHeader}>
        <h1 className={styles.title}>Reporting Center</h1>
        <div style={{ display: 'flex', gap: 8 }}>
          {['Procurement', 'Vendor', 'Risk', 'Compliance'].map(type => (
            <button key={type}
              style={{ background: '#0052cc', color: '#fff', border: 'none', padding: '8px 14px', borderRadius: 6, cursor: 'pointer', fontSize: 13 }}
              onClick={() => dispatch(generateReport(type))}
              disabled={generating}>
              {generating ? 'Generating...' : `+ ${type}`}
            </button>
          ))}
        </div>
      </div>
      <div className={styles.chartCard}>
        <DataTable columns={columns} data={reports} loading={loading} />
      </div>
    </div>
  )
}

export default ReportCenterPage